### ISSUE TITLE
Discuss the competitive advantages and possible adverse effects of project failure

### ISSUE THREAD

**Issue by kevinleung56** [dennisz01/ISDM#17]
Discuss the competitive advantages might be gained in developing the new information
system. Identify and discuss the possible adverse effects for this Business if its information
system project fails

**Comment by dennisz01** [comment]
The delivered system will drive operational excellence in the CMC - increasing profitability and market share.

**Comment by kevinleung56** [comment]
9bcc018abfb8a9a440c0d37e866ff4660d4e6fe7
ce6d7d39e16f483d6057b614c2e5d516d2832fc1

The above commits have completed this issue
